### ISSUE TITLE
What's the metric compared to original paper?

### ISSUE THREAD

**Issue by cwchenwang** [bsuleymanov/mip-nerf#1]
Hi, thanks for your awesome pytorch implementation. Could you tell us whether the metrics of this pytorch version differs from that in the orignial paper?

**Comment by bsuleymanov** [comment]
@cwchenwang Hi, sorry for the late reply, didn't notice the question. I haven't trained the model yet.

**Comment by bdfbdf321** [comment]
@bsuleymanov Hi! Thanks for ur pytorch-implement of mip nerf. I'm also interested in your version's results. Could u show some visual results or metrcis comparing with the original one.

**Comment by bsuleymanov** [comment]
@bdfbdf321 Hi! I don't have visual results and metric values now. I will upload them when I get them.
